### ISSUE TITLE
[DT Betweenlands] Trees should drop Weedwood Sticks.

### ISSUE THREAD

**Issue by MagmaSlime123** [DynamicTreesTeam/DynamicTrees-TheBetweenlands#3]
Like DT Aether, its trees don't drop usual sticks.

This should be the same system as DT Betweenlands, its trees should drop Weedwood sticks.

**Comment by supermassimo** [comment]
The planks from betweenlands trees create vanilla sticks when crafted, not weedwood sticks and as such will drop vanilla trees when chopped
