### ISSUE TITLE
Please update the required Betweenlands version. Server refuse to start due to this.

### ISSUE THREAD

**Issue by MagmaSlime123** [DynamicTreesTeam/DynamicTrees-TheBetweenlands#7]
Title.

https://pastebin.com/JBHYFB2T

![image](https://user-images.githubusercontent.com/51277766/221345927-788a0b7f-07e4-4f65-8fc9-58592e93c429.png)

**Comment by supermassimo** [comment]
Thats the minimum version, it will not work with anything lower.
